server:
  servlet:
    context-path: ${server.servlet.context-path}
  port: ${server.port}
spring:
  profiles:
    active: local
  datasource:
     driver-class-name: org.postgresql.Driver
     url: ${spring.datasource.url}
     username: ${spring.datasource.username}
     password: ${spring.datasource.password}
  jpa:
    open-in-view: true
    show-sql: ${spring.jpa.properties.hibernate.show_sql}
    properties:
      hibernate:
        format_sql: false
    hibernate: 
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
